// <auto-generated />
using System;
using Computer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Computer.Infrastructure.Migrations
{
    [DbContext(typeof(ComputerDbContext))]
    [Migration("20240205193937_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Computer.Domain.Entities.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EncodedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("Computer.Domain.Entities.Computer", b =>
                {
                    b.OwnsOne("Computer.Domain.Entities.ComputerSpecificationDetails", "SpecificationDetails", b1 =>
                        {
                            b1.Property<int>("ComputerId")
                                .HasColumnType("int");

                            b1.Property<string>("CPU")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GPU")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Memory")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ComputerId");

                            b1.ToTable("Computers");

                            b1.WithOwner()
                                .HasForeignKey("ComputerId");
                        });

                    b.Navigation("SpecificationDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
